jobs:
    build:
      docker:
        - image: sillelien/circleci-dollar-build-image
        - image: redis:3-alpine

      environment:
        MAJOR_VERSION: 0.3
        MAVEN_OPTS: "-Xmx1g -DbuildNumber=${CIRCLE_BUILD_NUM} -Dorg.xml.sax.driver='com.sun.org.apache.xerces.internal.parsers.SAXParser' "
        TZ: "/usr/share/zoneinfo/Europe/London"

      working_directory: ~/dollar

      branches:
        ignore:
          - gh-pages

      steps:

        - checkout

        - restore_cache:
            key: dependency-cache

        - run:
            name: dependencies
            command: |
              ~/build-utils/maven_make_deps.sh

        - save_cache:
            key: dependency-cache
            paths:
                - ~/.gnupg
                - ~/.m2
        - run:
            name: test
            command: |
                 mvn -q -T 1C -Drat.skip -Dsource.skip=true -DgenerateReports=false -Dmaven.javadoc.skip=true install
                 ./build-docs.sh
                 ./pack/pack.sh
            no_output_timeout: 600

#        - run:
#            name: build-docs
#            command: |
#
#
#        - run:
#            name: pack
#            command: |
#                

        - deploy:
            command: |
              if [ "${CIRCLE_BRANCH}" == "staging" ]; then
                      ~/build-utils/promote_from_staging.sh
              fi
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                      ~/build-utils/maven_deploy.sh
                      ./pack/upload.sh
              fi
